import * as z from "zod";
import { type FormTemplate } from "@/registry/default/types";

export const addressFormTemplate: FormTemplate = {
  id: "address-form",
  name: "Address Form",
  description: "Shipping or billing address collection",
  category: "ecommerce",
  schema: z.object({
    fullName: z.string().min(2, "Name must be at least 2 characters"),
    addressLine1: z.string().min(5, "Address is required"),
    addressLine2: z.string().optional(),
    city: z.string().min(2, "City is required"),
    state: z.string().min(2, "State/Province is required"),
    zipCode: z.string().min(3, "ZIP/Postal code is required"),
    country: z.string().min(2, "Country is required"),
    phone: z.string().regex(/^[0-9+\-\s()]*$/, "Invalid phone number").optional(),
  }),
  defaultValues: {
    fullName: "",
    addressLine1: "",
    addressLine2: "",
    city: "",
    state: "",
    zipCode: "",
    country: "",
    phone: "",
  },
  fields: [
    {
      type: "input",
      name: "fullName",
      label: "Full Name",
      placeholder: "John Doe",
      required: true,
      inputType: "text",
    },
    {
      type: "input",
      name: "addressLine1",
      label: "Address Line 1",
      placeholder: "123 Main Street",
      required: true,
      inputType: "text",
    },
    {
      type: "input",
      name: "addressLine2",
      label: "Address Line 2",
      placeholder: "Apt 4B (optional)",
      required: false,
      inputType: "text",
    },
    {
      type: "input",
      name: "city",
      label: "City",
      placeholder: "San Francisco",
      required: true,
      inputType: "text",
    },
    {
      type: "input",
      name: "state",
      label: "State / Province",
      placeholder: "CA",
      required: true,
      inputType: "text",
    },
    {
      type: "input",
      name: "zipCode",
      label: "ZIP / Postal Code",
      placeholder: "94102",
      required: true,
      inputType: "text",
    },
    {
      type: "input",
      name: "country",
      label: "Country",
      placeholder: "United States",
      required: true,
      inputType: "text",
    },
    {
      type: "input",
      name: "phone",
      label: "Phone Number",
      placeholder: "+1 (555) 123-4567",
      required: false,
      inputType: "tel",
    },
  ],
};
