import * as z from "zod";
import { type FormTemplate } from "@/registry/default/types";

export const onboardingWizardTemplate: FormTemplate = {
  id: "onboarding-wizard",
  name: "Onboarding Wizard",
  description: "Multi-step user onboarding process",
  category: "profile",
  schema: z.object({
    // Account
    email: z.string().email("Invalid email"),
    password: z.string().min(8, "Password must be at least 8 characters"),
    // Profile
    fullName: z.string().min(2, "Name is required"),
    bio: z.string().optional(),
    website: z.string().url("Invalid URL").optional().or(z.literal("")),
    // Preferences
    notifications: z.boolean().default(true),
    theme: z.enum(["light", "dark", "system"]),
  }),
  defaultValues: {
    email: "",
    password: "",
    fullName: "",
    bio: "",
    website: "",
    notifications: true,
    theme: "system",
  },
  fields: [], // Flattened fields will be generated by generator if we wanted, but here we define steps
  steps: [
    {
      id: "account",
      title: "Account",
      description: "Create your secure account",
      fields: [
        {
          type: "input",
          name: "email",
          label: "Email Address",
          placeholder: "john@example.com",
          required: true,
          inputType: "email",
        },
        {
          type: "input",
          name: "password",
          label: "Password",
          placeholder: "••••••••",
          required: true,
          inputType: "password",
        },
      ],
    },
    {
      id: "profile",
      title: "Profile",
      description: "Tell us about yourself",
      fields: [
        {
          type: "input",
          name: "fullName",
          label: "Full Name",
          placeholder: "John Doe",
          required: true,
          inputType: "text",
        },
        {
          type: "textarea",
          name: "bio",
          label: "Bio",
          placeholder: "I am a software engineer...",
        },
        {
          type: "input",
          name: "website",
          label: "Website",
          placeholder: "https://example.com",
          inputType: "url",
        },
      ],
    },
    {
      id: "preferences",
      title: "Preferences",
      description: "Customize your experience",
      fields: [
        {
          type: "select",
          name: "theme",
          label: "Theme Preference",
          required: true,
          options: [
            { label: "Light", value: "light" },
            { label: "Dark", value: "dark" },
            { label: "System", value: "system" },
          ],
        },
        {
          type: "checkbox",
          name: "notifications",
          label: "Enable Email Notifications",
        },
      ],
    },
  ],
};
